version: '3.8'

services:
  dev:
    container_name: library-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - uploads:/usr/src/app/uploads
    ports:
      - ${APP_PORT}:${APP_PORT}
      - "9229:9229"
    command: npm run start:dev
    environment:
      TZ: 'Europe/Warsaw'
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: library-database
    image: postgres:12
    environment:
      TZ: 'Europe/Warsaw'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      TZ: 'Europe/Warsaw'
      PGADMIN_DEFAULT_EMAIL: ${DB_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050/tcp"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
  uploads:
