export const METADATA = {
  id: { title: 'Identyfikator rekordu' },
  isbn: { title: 'ISBN' },
  title: { title: 'Tytuł' },
  description: { title: 'Opis' },
  image: { title: 'Identyfikator obrazka' },
  issueDate: { title: 'Data wydania' },
  publisher: { title: 'Wydawca' },
  authors: { title: 'Autorzy' },
  type: { title: 'Rodzaj' },
  genre: { title: 'Gatunek' },
  language: { title: 'Język' },
  pages: { title: 'Liczba stron' },
  tags: { title: 'Tagi' },
  details: { title: 'Szczegółowe informacje' },
  createdAt: { title: 'Moment utworzenia rekordu' },
  modifiedAt: { title: 'Moment modyfikacji rekordu' },
  removedAt: { title: 'Moment usunięcia rekordu' },
};

export const CONSTRAINTS = {
  isbn: {
    minLength: 10,
    maxLength: 13,
    nullable: false,
  },
  title: {
    maxLength: 255,
    nullable: false,
  },
  description: { nullable: true },
  image: { nullable: true },
  issueDate: { nullable: false },
  publisher: { nullable: false },
  authors: { nullable: false },
  type: { nullable: false },
  genre: { nullable: false },
  language: { nullable: false },
  pages: { nullable: false },
  tags: { nullable: false },
  details: { nullable: false },
  copies: { nullable: true },
  ratings: { nullable: true },
};
